### ISSUE TITLE
Connection dropping with multiple clients

### ISSUE THREAD

**Issue by arkonbob** [gonimo/gonimo#14] opened 2020-01-25 22:21 UTC
When I connect a second client concurrently I get frequent connection drops (flashing red screen and audible alert). The first client remains connected without issue. Chrome is being used on both host (baby) and client machines. If I disconnect the first client before connecting from the second, the new connection is stable.

The connection instability seems to coincide with this message in the client's browser console log:

`True                                       all-561927b39550fbc34e992f1845a9b852.min.js:205`

**Comment by eskimor** [comment] 2020-01-28 11:02
Thanks! I'll have a look!

**Comment by eskimor** [comment] 2020-01-28 11:09
I can't reproduce the issue. What version of Chrome are you using and on what devices? How good is your wifi reception? It could simply be a resource problem, like to little bandwidth or the baby station is overwhelmed, ..

**Comment by arkonbob** [comment] 2020-01-28 17:10
Just reproduced again today - the baby monitor had been running fine for 24 hours with at least 2 clients. Just reconnected for the afternoon nap and started seeing persistent connection issues. VNC'd into the box, closed and reopened chrome, reconnect the clients and everything's fine.

My guess is this issue would not be apparent on a more powerful host with plenty of spare resources.

**Comment by eskimor** [comment] 2020-01-29 13:18
Thanks for those details - in fact we had a resource leakage problem in the past, due to some browser weirdness. I thought we resolved it, but maybe it came back. I will have a look!

**Comment by arkonbob** [comment] 2020-01-29 22:42
Thanks. In case any other users have the same issue, my workaround for the time being is to close and re-open Chrome between baby naps. Because I want to make the baby station as close to an "appliance" as possible for my non-technical users, I have it set to do that automatically whenever the power button is pressed to suspend/resume the PC:

Create the following script and make it executable:

`/lib/systemd/system-sleep/restart-chrome`

The script content is:

`#!/bin/bash 

if [ "${1}" = "pre" ]; then
  # Do the thing you want before suspend here
  killall chrome
elif [ "${1}" = "post" ]; then
  # Do the thing you want after resume here
  su <username> -c "DISPLAY=:0 google-chrome --start-fullscreen --restore-last-session"
fi`

It closes the Chrome browser when the PC is suspended and reopens it for the logged in X user (I assume there is only ever one) when the PC is resumed. Gonimo is set to auto-start in monitor mode. Chrome is set to auto-start on boot too, so very little interaction is required at all.

**Comment by arkonbob** [comment] 2020-01-29 22:47
BTW my chrome version is 79.0.3945.130 64 bit

**Comment by eskimor** [comment] 2020-02-01 19:52
Thanks a lot @arkonbob ! :-)

**Comment by eskimor** [comment] 2020-02-01 19:59
Btw. you are talking about "non-technical" users - in what context do you use Gonimo? We always had this idea of Gonimo compatible appliances in our vision, so this sounds interesting :-)

**Comment by arkonbob** [comment] 2020-02-02 01:33
@eskimor by non-technical users, I mean grandma, grandpa, mum, the babysitter... anyone who doesn't share my passion for digging around the Linux internals, which is ... almost everyone ;-) If someone else is looking after my baby I want them to be able to use Gonimo to keep an eye on her.

I have learnt from years of building home theatre PCs that no matter what a system can do, it has to be really, really simple to use or other family members will give up on it. Which is fair enough, it is my hobby not theirs, they just want to watch TV or listen to music.

Gonimo is easy to use in a browser and the phone app is great. I can put it on the users home screen and just say 'click on this'. But when I first setup the Eee PC as a baby monitor, my instructions would have been:

1. Log in with this username and password.
2. Open Google Chrome.
3. Load Gonimo
4. When you are done, click the app menu, choose "Leave", then "Suspend".
5. Press a key or the power button when you want to wake the PC and start the baby monitor again.
6. Enter the password to unlock the PC.
7. If you have any connectivity issues, close the browser and reopen it.

I knew this probably wasn't going to fly. If I want my family members to use it, it has to be as simple as a baby monitor you would buy in a department store. The instructions for these are:

1. Press the power button to turn the baby monitor on and again to turn it off.

So I have configured the desktop (LXQT) to log in automatically. Chrome starts automatically in fullscreen (I think fullscreen is really important and a big step toward an appliance experience - having the browser and desktop panels visible adds clutter and confusion). Chrome is set to restore the previous session, so loads Gonimo automatically. Gonimo is set to start the baby monitor automatically and fortunately for me remembers to use the external IR webcam (the built-in camera is useless because the room is dark). There is one button on the exterior of the PC apart from power - I have configured this to trigger suspend. As discussed in my earlier post, suspend now kills and restarts Chrome, so that deals with any reliability issues. I have disabled xscreensaver so that a password is no longer required on resume. The screen is set to time out after 5 minutes inactivity (the wife complained that the screen was lighting up the room). My instructions are now:

1. Press the power button to start the baby monitor and again to turn it off.
2. Press the suspend button to pause the baby monitor between naps.

So I am pretty close to a simple, off-the-shelf baby monitor experience. Usually it is just step 2 anyway because we never turn the PC off.

Interesting that you should mention building appliances - I had been thinking you probably have quite a market out there if you go in that direction. I would be interested if you ever decide to go to market in the UK and need a representative :-)

I think you could build something with a SoC like the Raspberry Pi - the old V3 could probably handle it and is quite cheap now. It would simply need to run Chromium browser in kiosk mode and provide a way of configuring WiFi connections. Keeping the cost competitive while integrating an IR camera (essential) and touchscreen would be tricky though.

Also I think you would really need to get iOS compatibility sorted out first and preferably as an app rather than in-browser. It's a massive chunk of the market that you're missing right now. 

Lastly (this post is turning out a lot longer than I intended!) there is another option for monetisation besides a complete appliance. That is to add UVC camera support to the Android app and ship a camera module. As described earlier, I have an IR webcam that I believe is supported by Android (I still have to do more testing) but is not detected by the Gonimo app - I think you would have to enable support as described here:

https://source.android.com/devices/camera/external-usb-cameras

If you were to produce your own USB-OTG or wireless camera module for iOS and Android Gonimo apps, that would really add value. At the moment the camera feature in the Gonimo app is a bit of a gimmick - babies tend to nap in dark rooms and a normal phone camera isn't very useful. The camera I have was difficult to find and expensive for what it is. If you could package something like this

https://www.amazon.co.uk/MakerHawk-Raspberry-Camera-Vision-Adjustable/dp/B071718FDK/ref=sr_1_4?keywords=raspberry+pi+ir+camera&qid=1580605019&sr=8-4 

as a hardware add-on module for Gonimo at a competitive price point I think there could be a market for that.

**Comment by eskimor** [comment] 2020-02-02 05:25
Thanks a lot for sharing your insights! That's some really valuable feedback :-)

**Comment by eskimor** [comment] 2020-03-10 11:21
It is quite likely that this issue got fixed due to my fix for #15 - which is live in production now. @arkonbob does it work for you now?

**Comment by eskimor** [comment] 2020-03-10 15:01
Don't bother - it is not fixed :-(

**Comment by eskimor** [comment] 2020-03-11 09:07
Sane browsers decided to properly implement the insane spec: 
https://github.com/w3c/webrtc-pc/issues/1799
https://bugs.chromium.org/p/chromium/issues/detail?id=699036

Let's find a workaround ...

**Comment by eskimor** [comment] 2020-03-11 11:10
Should be fixed in production, could you have a look @arkonbob  - thanks! :-)

**Closed by eskimor** 2020-03-11 11:10 UTC

**Comment by arkonbob** [comment] 2020-03-11 18:34
Yup, can confirm this is fixed. It seems my server has a maximum capacity of 2 clients - above that there are occasional connection losses. But now when the the third client is disconnected, the others settle back to normal operation. 

See comments on #15 too - nice work, big improvements all round today, thanks! :-D

**Comment by arkonbob** [comment] 2020-03-11 19:12
@eskimor As a follow-up to the earlier discussion in this thread, I thought you might be interested to know that I've been successfully using a Raspberry Pi 3 as a Gonimo baby monitor when away from home. It's a bit smaller and lighter than the EeePC on the road and doesn't need a dedicated power supply. I take the same IR camera with me and I've added a cheap USB microphone to the Pi so that we can get audio. 

The only difficulty is that it's headless, so I have to VNC to the Pi from a phone/iPad/laptop if anything needs to be configured (usually local network access). Most of the time I just connect it to my travel router via ethernet and power it up, the router handles connection to the local network. I have a spare USB WiFi dongle lying around, at some point I may set up RaspAP [https://raspap.com/](url). Then the Pi can take on the role of the travel router, with the built in WiFi configured as a hotspot. After connecting to the hotspot, connection to the local network using the dongle can be configured in the RaspAP GUI.

**Comment by eskimor** [comment] 2020-03-11 20:37
That's indeed interesting - thanks for sharing! :-)
